general:
  out_dir: data/processed/kg4fun/dataset1/schema
class:
  general:
    out_dir: &local_outdir data/interim/kg4fun/dataset1/schema
    pbar: &pbar True
  data:
    name: data/raw/kg4fun/dataset1/node_types/summarization/qwen3-8b/node_type_info.json
rel:
  general:
    out_dir: *local_outdir
    pbar: *pbar
  data:
    name: data/raw/kg4fun/dataset1/edge_types/summarization/qwen-8b/edge_type_info.json
    