general:
  out_dir: data/processed/kg4fun/dataset2/alignment
  pbar: True
ontology:
  input_kg: data/processed/kg4fun/dataset2/input_kg/processed_ontology.json
  schema: data/processed/kg4fun/dataset2/schema/processed_ontology.json
alignment:
  node_types: data/raw/kg4fun/dataset2/node_types.json
  connected_components: data/raw/kg4fun/dataset2/edges/connected_components.json
  num_class_negative: 0
  num_rel_negative: 0
