from .ontomap_starting_kg4fun_processor import OntomapStartingKG4FUNProcessor
from .ontomap_schema_kg4fun_processor import OntomapSchemaKG4FUNProcessor
from .ontomap_kg4fun_alignment_processor import OntomapKG4FUNAlignmentProcessor